server:
  port: 9001
  error:
    include-stacktrace: never

spring:
  application:
    name: dishes-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_meal
    username: root
    password: 5cdrn6rc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
